feat: install in user app not rott but nix-channel or nix-env would still mount proc error

diff --git a/config/home/app/Desktop/Install_SOFTWARE/nix-install b/config/home/app/Desktop/Install_SOFTWARE/nix-install
--- a/config/home/app/Desktop/Install_SOFTWARE/nix-install
+++ b/config/home/app/Desktop/Install_SOFTWARE/nix-install
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 set -e
-
+# umask是确定掩码设置的命令，该掩码控制如何为新创建的文件设置文件权限
 umask 0022
 
 dest="/nix"
@@ -121,9 +121,10 @@ while [ $# -gt 0 ]; do
     esac
     shift
 done
-
+echo $USER
 if [ "$INSTALL_MODE" = "daemon" ]; then
     printf '\e[1;31mSwitching to the Multi-user Installer\e[0m\n'
+    # ACTIONS install
     exec "$self/install-multi-user" $ACTIONS # let ACTIONS split
     exit 0
 fi
@@ -160,12 +161,14 @@ for i in $(cd "$self/store" >/dev/null && echo ./*); do
     if [ -t 0 ]; then
       printf "." >&2
     fi
+    # $$ is pid
     i_tmp="$dest/store/$i.$$"
     if [ -e "$i_tmp" ]; then
         rm -rf "$i_tmp"
     fi
     if ! [ -e "$dest/store/$i" ]; then
         cp -RPp "$self/store/$i" "$i_tmp"
+        # 对文件的所有用户ugo删除写w权限  # -R 目录docs和其子目录
         chmod -R a-w "$i_tmp"
         chmod +w "$i_tmp"
         mv "$i_tmp" "$dest/store/$i"
@@ -182,7 +185,7 @@ fi
 # shellcheck source=./nix-profile.sh.in
 . "$nix/etc/profile.d/nix.sh"
 
-if ! "$nix/bin/nix-env" -i "$nix"; then
+if ! "$nix/bin/nix-env" --option sandbox false -i "$nix"; then
     echo "$0: unable to install Nix into your default profile" >&2
     exit 1
 fi
@@ -195,15 +198,17 @@ fi
 
 # Subscribe the user to the Nixpkgs channel and fetch it.
 if [ -z "$NIX_INSTALLER_NO_CHANNEL_ADD" ]; then
+echo "nix is: $nix"
     if ! "$nix/bin/nix-channel" --list | grep -q "^nixpkgs "; then
-        "$nix/bin/nix-channel" --add https://nixos.org/channels/nixpkgs-unstable
+        # "$nix/bin/nix-channel" --add https://nixos.org/channels/nixpkgs-unstable
+        nix-channel --add https://mirrors.ustc.edu.cn/nix-channels/nixpkgs-unstable nixpkgs
     fi
-    if [ -z "$_NIX_INSTALLER_TEST" ]; then
-        if ! "$nix/bin/nix-channel" --update nixpkgs; then
-            echo "Fetching the nixpkgs channel failed. (Are you offline?)"
-            echo "To try again later, run \"nix-channel --update nixpkgs\"."
-        fi
-    fi
+    # if [ -z "$_NIX_INSTALLER_TEST" ]; then
+    #     if ! "$nix/bin/nix-channel" --update nixpkgs; then
+    #         echo "Fetching the nixpkgs channel failed. (Are you offline?)"
+    #         echo "To try again later, run \"nix-channel --update nixpkgs\"."
+    #     fi
+    # fi
 fi
 
 added=
@@ -233,7 +238,7 @@ if [ -z "$NIX_INSTALLER_NO_MODIFY_PROFILE" ]; then
         fi
     done
 fi
-
+echo "added is: $added"
 if [ -z "$added" ]; then
     cat >&2 <<EOF
 
@@ -253,5 +258,10 @@ variables are set, either log in again, or type
   . $p
 
 in your shell.
+EOF
+echo >>~/.profile <<EOF
+if ! . /home/app/.nix-profile/etc/profile.d/nix.sh; then
+    echo "nix don't install"
+fi
 EOF
 fi
